/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_INCLUDE_DATA                        0
#define GD_EXCLUDE_ICONS                       1
#define GD_CONFIRM	                           2
#define GD_ADD		                           3
#define GD_DONE	    	                       4

#define FWDIR_CNT 5

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *FWDIRWnd;
extern struct Gadget        *FWDIRGList;
extern struct Gadget        *FWDIRGadgets[FWDIR_CNT];
extern struct IClass        *getClass;
extern struct _Object       *getImage;
extern UWORD                 FWDIRLeft;
extern UWORD                 FWDIRTop;
extern UWORD                 FWDIRWidth;
extern UWORD                 FWDIRHeight;
extern UBYTE                 FWDIRWdt[];
extern struct TextAttr       topaz8;
extern UWORD                 FWDIRGTypes[];
extern struct NewGadget      FWDIRNGad[];
extern ULONG                 FWDIRGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void FWDIRRender( void );
extern int OpenFWDIRWindow( void );
extern void CloseFWDIRWindow( void );
