/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_PATCHLIST                            0
#define GD_EXIT                                1

#define GDX_PATCHLIST                           0
#define GDX_EXIT                               1

#define Patch_CNT 2

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *PatchWnd;
extern struct Gadget        *PatchGList;
extern struct Gadget        *PatchGadgets[2];
extern UWORD                 PatchLeft;
extern UWORD                 PatchTop;
extern UWORD                 PatchWidth;
extern UWORD                 PatchHeight;
extern UBYTE                *PatchWdt;
extern struct TextAttr       topaz8;
extern UWORD                 PatchGTypes[];
extern struct NewGadget      PatchNGad[];
extern ULONG                 PatchGTags[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];


extern int OpenPatchWindow( void );
extern void ClosePatchWindow( void );
