/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_P_DECRUNCH_FILES                    0
#define GD_P_OVERWRITE_CRUNCHED_FILES          1
#define GD_P_SKIP_ENCRYPTED                    2
#define GD_P_CHECK_DATA_FILES                  3
#define GD_P_EXTRACT_ARCHIVES                  4
#define GD_P_NA						           5
#define GD_P_NA1		                       6
#define GD_P_SKIP_DAYS				  		   7
#define GD_P_DAYS_COUNT						   8
#define GD_P_FAST_FILE_CHECKING				   9
#define GD_P_LOGGING			              10
#define GD_P_LOG_PATH						  11
#define GD_P_FILE							  12
#define GD_P_ICONIFY						  13

#define Prefs_CNT 14

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *PrefsWnd;
extern struct Gadget        *PrefsGList;
extern struct Gadget        *PrefsGadgets[Prefs_CNT];
extern UWORD                 PrefsLeft;
extern UWORD                 PrefsTop;
extern UWORD                 PrefsWidth;
extern UWORD                 PrefsHeight;
extern UBYTE                *PrefsWdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      PrefsIText[];
extern UWORD                 PrefsGTypes[];
extern struct NewGadget      PrefsNGad[];
extern ULONG                 PrefsGTags[];
extern Class	          *initGet( void );
extern struct IClass        *getClass;
extern struct _Object       *getImage;


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void PrefsRender( void );
extern int OpenPrefsWindow( void );
extern void ClosePrefsWindow( void );
