/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SHOWLIST                            0
#define GD_EXIT                                1

#define GDX_SHOWLIST                           0
#define GDX_EXIT                               1

#define Show_CNT 2

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *ShowWnd;
extern struct Gadget        *ShowGList;
extern struct Gadget        *ShowGadgets[2];
extern UWORD                 ShowLeft;
extern UWORD                 ShowTop;
extern UWORD                 ShowWidth;
extern UWORD                 ShowHeight;
extern UBYTE                *ShowWdt;
extern struct TextAttr       topaz8;
extern UWORD                 ShowGTypes[];
extern struct NewGadget      ShowNGad[];
extern ULONG                 ShowGTags[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenShowWindow (ULONG lines, UWORD length);
extern void CloseShowWindow( void );
