/*
 *  Source machine generated by GadToolsBox V2.0
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_VirusView                            0

#define GDX_VirusView                           0

#define Virus_CNT 1

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *VirusWnd;
extern struct Gadget        *VirusGList;
extern struct Gadget        *VirusGadgets[1];
extern struct Menu          *VirusMenus;
extern UWORD                 VirusLeft;
extern UWORD                 VirusTop;
extern UWORD                 VirusWidth;
extern UWORD                 VirusHeight;
extern UBYTE                *VirusWdt;
extern struct TextAttr       topaz8;
extern struct NewMenu        VirusNewMenu[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];


extern int SetupScreen( void );
extern void CloseDownScreen ( void );
extern int OpenVirusWindow( void );
extern void CloseVirusWindow( void );

extern UBYTE Ver[];
extern UWORD screenWidth, screenHeight;
