/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_VOL_1                               0

#define GDX_VOL_1                              0

#define CheckAll_CNT 20

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *CheckAllWnd;
extern struct Gadget        *CheckAllGList;
extern struct Gadget        *CheckAllGadgets[CheckAll_CNT];
extern UWORD                 CheckAllLeft;
extern UWORD                 CheckAllTop;
extern UWORD                 CheckAllWidth;
extern UWORD                 CheckAllHeight;
extern UBYTE                *CheckAllWdt;
extern struct TextAttr       topaz8;
extern UWORD                 CheckAllGTypes[];
extern struct NewGadget      CheckAllNGad[];
extern ULONG                 CheckAllGTags[];
extern UWORD                 DriPens[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int OpenCheckAllWindow (UBYTE max );
extern void CloseCheckAllWindow( void );
