/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Jan Erik Olausen
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_P_DECRUNCH_FILES                    0
#define GD_P_CHECK_DATA_FILES                  1
#define GD_P_EXTRACT_LHA                       2
#define GD_P_EXTRACT_LZX                       3
#define GD_P_EXTRACT_ZIP                       4
#define GD_P_HIDE_KNOWN_PATCHES                5

#define GDX_P_DECRUNCH_FILES                   0
#define GDX_P_CHECK_DATA_FILES                 1
#define GDX_P_EXTRACT_LHA                      2
#define GDX_P_EXTRACT_LZX                      3
#define GDX_P_EXTRACT_ZIP                      4
#define GDX_P_HIDE_KNOWN_PATCHES                5

#define Project0_CNT 6

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *Project0Wnd;
extern struct Gadget        *Project0GList;
extern struct Gadget        *Project0Gadgets[5];
extern UWORD                 Project0Left;
extern UWORD                 Project0Top;
extern UWORD                 Project0Width;
extern UWORD                 Project0Height;
extern UBYTE                *Project0Wdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      Project0IText[];
extern UWORD                 Project0GTypes[];
extern struct NewGadget      Project0NGad[];
extern ULONG                 Project0GTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void Project0Render( void );
extern int OpenProject0Window( void );
extern void CloseProject0Window( void );
